### PR TITLE
Fixed issues with Specials in TV Seasons, display of thumbnail on now playing screen, Added pre-fetching of covers on lists

### PR DESCRIPTION
**Pull request by natbur**
Season 0 now interpreted as "Specials" this is in line with XBMC and fixes cover art for the Specials season as well as the displayed text
moved the download code for the now playing screen into the connection class and use the methods there to get the connection.  this fixes a problem with 401 being returned from XBMC when requesting the thumbnail
Added pre-fetching of covers that are in cache (from disk to mem).  And load covers from memCache synchronously when an item id drawn.  This prevents the flashing from the 'default' to the final cover when scrolling a list.

### CODE REVIEW

**Comment by natbur** [comment]
the thumbnails problem is on google code here:
http://code.google.com/p/android-xbmcremote/issues/detail?id=598

**Comment by freezy** [comment]
Looks good at first glance! Will test and merge later this week.

Cheers!

**Comment by natbur** [comment]
Sorry for piling on the commits, new to git and still figuring it out.  Didn't realize that it updates the pull request range when I commit new changes.  I think I've got it sorted now, if you want me to break up the pull requests for you I can.

**Comment by freezy** [comment]
Nah no problem.

**Comment by natbur** [comment]
Hold off on merging this in.  I found an OutOfMemory error that I need to fix first

**Comment by natbur** [comment]
Alright, I think I've got everything working smoothly now.  I've tested it on my SGSII and my TF101 across 2.3.4, 3.2 and 4.0.3
Should be good to merge in now

**Comment by gostaj** [comment]
Thanks Natbur for your fixes! Freezy: when can this be merged and released?
Asking on behalf of us waiting for the fix for this:
https://code.google.com/p/android-xbmcremote/issues/detail?id=598

**Comment by freezy** [comment]
Sorry got completely driven away by work these days. Will release a build for testing ASAP. Don't hesitate nagging in here ;)

**Comment by freezy** [comment]
Sorry guys it took so long. Will run some more tests and release a new version soon.

**Pull request merged**
