### PR TITLE
JSONRPC API Support

### PR DESCRIPTION
**Pull request by tthomas48**
JSONRPC support added for Eden and somewhat for Frodo. You can enable and disable it in the settings.

### CODE REVIEW

**Comment by freezy** [comment]
Any way you could update so it can be merged? I've started to rip out HTTPAPI out of the current remote but it's deeper in there than I thought. I think I'll just try to make this work with Frodo and focus on the new version then.

**Comment by tthomas48** [comment]
Sure. I'll try to get this working. I'm planning on constructing the ConnectionManager in the JSONClient and then passing that into the clients instead of the old Connection. I'm also going to rip out all the Version detection stuff in favor of Frodo based code.
Let me know if either of those assumptions are wrong.

**Comment by freezy** [comment]
Yep, dropping support for Eden is acceptable in this case.

**Comment by tthomas48** [comment]
I noticed you marked MusicClient.getAlbums as basically deprecated. Is your
goal to just have the calls to the ConnectionManager directly in the
Activities and get rid of the whole Activity->Manager->Client layer?

**Comment by tthomas48** [comment]
Nevermind. It looks like it will fit nicely into the Manager layer.

**Comment by freezy** [comment]
Cool!

**Pull request closed without merging**
