### PR TITLE
Ant build scripts

### PR DESCRIPTION
**Pull request by rom1v**
Generated by:
  android update project -p <path> -n android-xbmcremote

For build apk in commandline (without Eclipse).

### CODE REVIEW

**Comment by elangelo** [comment]
doesn't work for me..

**Comment by rom1v** [comment]
What is the problem ?

You need the modifications from this pull request too :
https://github.com/freezy/xbmc-jsonrpclib-android/pull/4

I should detail :

```
git clone https://github.com/rom1v/android-xbmcremote.git -b build
git clone https://github.com/rom1v/xbmc-jsonrpclib-android.git -b build
# adapt YOUR_ANDROID_SDK_PATH
echo sdk.dir=YOUR_ANDROID_SDK_PATH | tee {android-xbmcremote,xbmc-jsonrpclib-android}/local.properties
cd android-xbmcremote
# then, for example
ant debug # generate bin/android-xbmcremote-debug.apk
```

Please don't hesitate if something goes wrong after that.

**Comment by elangelo** [comment]
I realized this after I posted my comment, sorry for the noise.

Would you mind telling me how i can get a release build i can install on my phone (signed...)

**Comment by rom1v** [comment]
You can install the debug version on your phone:

```
adb install file-debug.apk
```

If you want to release and sign automatically, in `local.properties` (in both projects), just add:

```
key.store=YOUR_KEYSTORE_FILE
key.alias=YOUR_KEY_ALIAS
```

Then execute:

```
ant release
```

It will ask for your keystore and alias passwords. If you don't want it to ask, add:

```
key.store.password=KEYSTORE_PASSWORD
key.alias.password=KEY_ALIAS_PASSWORD
```

**Comment by rom1v** [comment]
Generated independently: https://github.com/freezy/android-xbmcremote/commit/7ced38a858d441367865eb29cdee602cc6a93aff

**Pull request closed without merging**
