### PR TITLE
Fixes issue #101

### PR DESCRIPTION
**Pull request by melo0187**
Fixes issue #101: Sharing videos from youtube app to xbmcremote stopped working because
Intent.EXTRA_TEXT contained more than just the url and the url itself
changed to a short version (youtu.be/videoID)

### CODE REVIEW

**Comment by melo0187** [comment]
I'm sorry that this pull request also contains a "revert" commit I did by accident. I didn't mean to add this useless commit to the pull request nor did I mean to revert the commit in the first place. This is my first fork->-branch->fix->request-pull, hence the mistake. I would be glad to correct this mistake, if anyone could be so kind to explain how.

Thanks in advance!
melo

**Comment by gthazmatt** [comment]
I don't know the policy of this group, but it's common to want to keep the history clean, so they may reject the pull request and ask that you fix your branch before submitting another. You would need to use rebasing to fix it (http://git-scm.com/book/en/Git-Branching-Rebasing). In this position (I see you just added an undo commit), I would do "git rebase -i HEAD~4" (can also use the hash of the common branch) and simply remove both the initial and undo commits from the commit list. The changes would be discarded, and you would be left with just the one commit on top of master. You would also need to push to a different remote repository.

**Comment by tombriden** [comment]
Normally you'd be right but as this is a small, rarely updated project I'll just cherry pick the relevant commit and close off this request when I'm at my pc tomorrow :)

**Comment by melo0187** [comment]
@gthazmatt thank you very much for the reply. Even if not needed in this situation as @tombriden said, I will look into rebasing so that I can learn how to fix this silly mistakes, because all I wanted was to contribute a fix and not litter the commit history. I'm sorry for the inconvenience. As I said this is basically my first git/github experience and I'm still learning.

**Comment by tombriden** [comment]
I've cherry-picked the 2 commits so will now close this off. If you need to do any further changes then start a new branch and pull request.

**Pull request closed without merging**
