### PR TITLE
Let's try this again

### PR DESCRIPTION
**Pull request by tthomas48**
The previous version couldn't run on earlier android versions (specifically Froyo). I fixed that. I'll try to start using issues to track changes from here on out.

### CODE REVIEW

**Comment by DjSlash** [comment]
Hi Tim Thomas,
I've tried the new build you created yesterday, it connects perfectly to my xbmc (12 beta 2) using the JSON, but it's quite unstable. It crashes in various accasions, haven't found a common cause yet. It's ofcourse hard to say if it is your build specificly, since I can't test the orginal app. Just wanted to give you a heads up.

**Comment by tthomas48** [comment]
Thanks for testing. I'm definitely expecting some instability. There's a lot of new code in there. The JSONRPC stuff keeps a connection open as well so I think I need to work on making it more robust when the network is going in and out.
I've uploaded a newer build with ACRA integrated. This will prompt you to send emails if errors occur. You can always also file bug reports based on the info. There's no difference between the two builds except the error reporting, so if it gets annoying you can move to the previous one.

**Comment by freezy** [comment]
First tests very promising! Thanks a lot, Tim.

**Comment by freezy** [comment]
Public build for testing can be downloaded here:

http://forum.xbmc.org/showthread.php?tid=147741

**Pull request merged**
